import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { RLE } from "../src/rle.mjs";
import { cleanString } from "../src/utils.mjs";

describe("RLE", () => {
  test("can read a .rle file", () => {
    expect(RLE.fromFile("./test/shapes/gosper_glider_gun.rle").toString().startsWith("#N Gosper glider gun")).to.be
      .true;
  });
  test("can decode simple pattern", () => {
    expect(RLE.decode("2obo$2$1o2$!", 6, 6)).to.deep.equal(
      cleanString(`
        xx.x..
        ......
        ......
        x.....
        ......
        ......
      `),
    );
  });
  test.skip("can produce a Pattern", () => {
    expect(RLE.fromFile("./test/shapes/gosper_glider_gun.rle").toPattern().characters).to.deep.equal(
      cleanString(`
        ........................x...........
        ......................x.x...........
        ............xx......xx............xx
        ...........x...x....xx............xx
        xx........x.....x...xx..............
        xx........x...x.xx....x.x...........
        ..........x.....x.......x...........
        ...........x...x....................
        ............xx......................
      `),
    );
  });
});
