import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { RLE } from "../src/rle.mjs";
import { cleanString } from "../src/utils.mjs";

describe("RLE decoding", () => {
  test("works on empty pattern", () => {
    expect(RLE.decode("!", 3, 3)).to.deep.equal(
      cleanString(`
        ...
        ...
        ...
      `),
    );
  });
  test("works on simple pattern", () => {
    expect(RLE.decode("2obo3$o3$!", 6, 6)).to.deep.equal(
      cleanString(`
        xx.x..
        ......
        ......
        x.....
        ......
        ......
      `),
    );
  });
  test("works on more complex pattern", () => {
    expect(RLE.decode("$5bo2bo$2bo3bob$8b2o$2o2$5bo!", 10, 10)).to.deep.equal(
      cleanString(`
        ..........
        .....x..x.
        ..x...x...
        ........xx
        xx........
        ..........
        .....x....
        ..........
        ..........
        ..........
      `),
    );
  });
});

describe("RLE encoding", () => {
  test("works on empty pattern", () => {
    expect(
      RLE.encode(
        cleanString(`
        ...
        ...
        ...
      `),
        3,
        3,
      ),
    ).to.equal("!");
  });
  test("works on simple pattern", () => {
    expect(
      RLE.encode(
        cleanString(`
        xx.x..
        ......
        ......
        x.....
        ......
        ......
      `),
        6,
        6,
      ),
    ).to.equal("2obo3$o3$!");
  });
  test("works on more complex pattern", () => {
    expect(
      RLE.encode(
        cleanString(`
        ..........
        .....x..x.
        ..x...x...
        ........xx
        xx........
        ..........
        .....x....
        ..........
        ..........
        ..........
      `),
        10,
        10,
      ),
    ).to.equal("$5bo2bo$2bo3bo$8b2o$2o2$5bo4$!");
  });
  test("works on gosper glider gun", () => {
    expect(
      RLE.encode(
        cleanString(`
        ........................x...........
        ......................x.x...........
        ............xx......xx............xx
        ...........x...x....xx............xx
        xx........x.....x...xx..............
        xx........x...x.xx....x.x...........
        ..........x.....x.......x...........
        ...........x...x....................
        ............xx......................
      `),
        36,
        9,
      ),
    ).to.equal("24bo$22bobo$12b2o6b2o12b2o$11bo3bo4b2o12b2o$2o8bo5bo3b2o$2o8bo3bob2o4bobo$10bo5bo7bo$11bo3bo$12b2o$!");
  });
});

describe("RLE", () => {
  test("can read a .rle file", () => {
    expect(RLE.fromFile("./test/shapes/gosper_glider_gun.rle").toString().startsWith("#N Gosper glider gun")).to.be
      .true;
  });
  test("can produce a Pattern", () => {
    expect(RLE.fromFile("./test/shapes/gosper_glider_gun.rle").toPattern().characters).to.deep.equal(
      cleanString(`
        ........................x...........
        ......................x.x...........
        ............xx......xx............xx
        ...........x...x....xx............xx
        xx........x.....x...xx..............
        xx........x...x.xx....x.x...........
        ..........x.....x.......x...........
        ...........x...x....................
        ............xx......................
      `),
    );
  });
});
